
//swagger file 
const swaggerAutogen=require('swagger-autogen')();


//import swagger definitions from data/swaggerdefinitions.js
const swaggerDefinitions=require('./data/swaggerdefinitions.js');

const doc= {
    info: {
        version:"1.0.0",
        title:"Todo API",
        description:"Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host:"localhost:3000",
    definitions: {
        ...swaggerDefinitions //importing swagger definitions
        
    },
    components: {
        securitySchemes: {
            bearerAuth: {
                type:"http",
                in:"header",
                description:"JWT Authorization header using the Bearer scheme. Example: \"Authorization: Bearer {token}\"",
                scheme:"bearer",
                bearerFormat:"JWT"
            },
        },
    },
    security: [
        {
            bearerAuth: []
        }
    ]

};

const outputFile='./swagger_output.json';
const endpointsFiles=['./app.js'];


swaggerAutogen(outputFile,endpointsFiles,doc).then(()=> {
    require('./bin/www');
});
